# This workflow will build a Java project with Maven and cache/restore any dependencies to improve the workflow execution time
name: GitHub Actions Demo Test Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean
      - name: Build with Maven
        run: mvn install -Dtest=JenkinsTest -Dheadless=set
      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Run Tests            # Name of the check run which will be created
          path: "**/surefire-reports/TEST-*.xml"    # Path to test results
          reporter: java-junit    
      
